version: "3.9"

services:

  fetch:
    build: 
      context: ./
    container_name: iedsa_fetch
    env_file:
      - ./.env
    volumes: 
      - "./public:/public"
      - "./src:/src"
    command: ["/usr/bin/tail", "-f", "/dev/null"]